[features]
hide = [
    # missing dependency: pulldown-cmark-to-cmark ^10.0.1
    "cleanup-markdown",
]

[requires]
build = [
    "protobuf-devel",
]
lib = [
    "protobuf-devel",
]

[tests]
skip = [
    "tests::test_generate_no_empty_outputs",
    "tests::test_generate_deprecated",
]
skip-exact = true
comments = [
    "test_generate_no_empty_outputs: requires a files not included in published crates",
    "test_generate_deprecated: test fails on epel9 due to version of protobuf",
]
