[features]
enable-all = true

[package]
cargo-toml-patch-comments = [
    "- Remove criterion (benchmark only)",
    "- Widen mockall dependency",
    "  (see https://github.com/metrics-rs/metrics/pull/499)",
]

